### ISSUE TITLE
'ImportError: No module named _constant_time' when trying to generate ASAP token

### ISSUE THREAD

**Issue by nraghun** [atlassian/asap-authentication-python#56]
Hi,

I am trying to create ASAP token in MuleSoft using python but I am getting an error:
```
Root Exception stack trace:
Traceback (most recent call last):
  File "<script>", line 8, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atlassian_jwt_auth/signer.py", line 49, in generate_jwt
    return jwt.encode(
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jwt/api_jwt.py", line 55, in encode
    return super(PyJWT, self).encode(
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jwt/api_jws.py", line 102, in encode
    key = alg_obj.prepare_key(key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jwt/api_jws.py", line 102, in encode
    key = alg_obj.prepare_key(key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jwt/algorithms.py", line 205, in prepare_key
    key = load_pem_private_key(key, password=None, backend=default_backend())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jwt/algorithms.py", line 205, in prepare_key
    key = load_pem_private_key(key, password=None, backend=default_backend())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 74, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 29, in _available_backends
    ep.resolve() if hasattr(ep, "resolve") else ep.load(require=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/backends/commoncrypto/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.commoncrypto.backend import backend
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/backends/commoncrypto/backend.py", line 11, in <module>
    from cryptography.hazmat.backends.commoncrypto.ciphers import (
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/backends/commoncrypto/ciphers.py", line 11, in <module>
    from cryptography.hazmat.primitives import ciphers, constant_time
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: No module named _constant_time
```

I followed the steps in Readme: 
My python script includs:
```
import atlassian_jwt_auth
signer = atlassian_jwt_auth.create_signer(issuer, key_id, private_key_pem)
a_jwt = signer.generate_jwt(audience)
```

In MuleSoft python script module, I gave values to the variables - _issuer, key_id, private_key_pem, audience_. Also, _python.path_ is set to _/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages_
where _atlassian_jwt_auth_ folder is present after running _pip install atlassian_jwt_auth_

MuleSoft uses Jython engine for Python.

Thanks
Neeti

**Comment by dbaxa** [comment]
It seems to be that compiled modules are not available under `Jython` so the cryptography package isn't available (https://stackoverflow.com/a/40751910).
